frr defaults traditional
hostname br1-ce-01
log stdout
! rsyslog on the lab EC2 reads this file through the bind mount and sends it to Telegraf (Telegraf EC2), which writes it to the Kafka topic "logs"
log file /var/log/frr/frr.log informational
service integrated-vtysh-config
!
interface lo
 ip address 10.255.0.13/32
!
interface eth1
 description WAN to carrier-pe-01 100M
 ip address 172.16.4.2/30
!
interface eth2
 description LAN 1G
 ip address 10.3.0.1/24
!
router bgp 65003
 bgp router-id 10.255.0.13
 bgp log-neighbor-changes
 no bgp ebgp-requires-policy
 neighbor 172.16.4.1 remote-as 65000
 neighbor 172.16.4.1 description carrier-pe-01
 neighbor 172.16.4.1 timers 10 30
 !
 address-family ipv4 unicast
  network 10.3.0.0/24
  network 10.255.0.13/32
 exit-address-family
exit
!
