frr defaults traditional
hostname br2-ce-01
log stdout
service integrated-vtysh-config
!
interface lo
 ip address 10.255.0.14/32
!
interface eth1
 description WAN to carrier-pe-02
 ip address 172.16.5.2/30
!
interface eth2
 description LAN
 ip address 10.4.0.1/24
!
router bgp 65004
 bgp router-id 10.255.0.14
 no bgp ebgp-requires-policy
 neighbor 172.16.5.1 remote-as 65000
 neighbor 172.16.5.1 description carrier-pe-02
 neighbor 172.16.5.1 timers 10 30
 !
 address-family ipv4 unicast
  network 10.4.0.0/24
  network 10.255.0.14/32
 exit-address-family
exit
!
