frr defaults traditional
hostname carrier-pe-01
log stdout
! rsyslog on the lab EC2 reads this file through the bind mount and sends it to Telegraf (Telegraf EC2), which writes it to the Kafka topic "logs"
log file /var/log/frr/frr.log informational
service integrated-vtysh-config
!
interface lo
 ip address 10.255.0.1/32
!
interface eth1
 description hq-ce-01 primary access 1G
 ip address 172.16.1.1/30
!
interface eth2
 description br1-ce-01 access 100M
 ip address 172.16.4.1/30
!
interface eth5
 description carrier-pe-02 core 10G
 ip address 172.16.255.1/30
!
router bgp 65000
 bgp router-id 10.255.0.1
 bgp log-neighbor-changes
 no bgp ebgp-requires-policy
 neighbor 172.16.255.2 remote-as 65000
 neighbor 172.16.255.2 description carrier-pe-02
 neighbor 172.16.1.2 remote-as 65001
 neighbor 172.16.1.2 description hq-ce-01-primary
 neighbor 172.16.1.2 timers 10 30
 neighbor 172.16.4.2 remote-as 65003
 neighbor 172.16.4.2 description br1-ce-01
 neighbor 172.16.4.2 timers 10 30
 !
 address-family ipv4 unicast
  neighbor 172.16.255.2 next-hop-self
 exit-address-family
exit
!
