frr defaults traditional
hostname carrier-pe-02
log stdout
! Telegraf (inputs.tail) reads this file on the lab EC2 through the bind mount and sends it to the Kafka topic "logs"
log file /var/log/frr/frr.log informational
service integrated-vtysh-config
!
interface lo
 ip address 10.255.0.2/32
!
interface eth1
 description hq-ce-01 secondary access 100M
 ip address 172.16.2.1/30
!
interface eth2
 description dc-ce-01 access 1G
 ip address 172.16.3.1/30
!
interface eth3
 description br2-ce-01 access 100M
 ip address 172.16.5.1/30
!
interface eth5
 description carrier-pe-01 core 10G
 ip address 172.16.255.2/30
!
router bgp 65000
 bgp router-id 10.255.0.2
 bgp log-neighbor-changes
 no bgp ebgp-requires-policy
 neighbor 172.16.255.1 remote-as 65000
 neighbor 172.16.255.1 description carrier-pe-01
 neighbor 172.16.2.2 remote-as 65001
 neighbor 172.16.2.2 description hq-ce-01-secondary
 neighbor 172.16.2.2 timers 10 30
 neighbor 172.16.3.2 remote-as 65002
 neighbor 172.16.3.2 description dc-ce-01
 neighbor 172.16.3.2 timers 10 30
 neighbor 172.16.5.2 remote-as 65004
 neighbor 172.16.5.2 description br2-ce-01
 neighbor 172.16.5.2 timers 10 30
 !
 address-family ipv4 unicast
  neighbor 172.16.255.1 next-hop-self
 exit-address-family
exit
!
